services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authenticator
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - poznit-network
  app:
    image: pozniako/authenticator
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "6767:6767"
    networks:
      - poznit-network

volumes:
  db_data:
networks:
  poznit-network:
    driver: bridge
