services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authenticator
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - poznit-network
  flyway:
    image: pozniako/flyway
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://db:5432/authenticator
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - poznit-network
    restart: no
  app:
    image: pozniako/authenticator
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - flyway
    ports:
      - "6767:6767"
    networks:
      - poznit-network

volumes:
  db_data:
networks:
  poznit-network:
    driver: bridge
