name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cargo lock check
      run: cargo check --locked

  docker-build-release:
    needs: checks
    uses: poznit/workflows/.github/workflows/template-build-release.yml@main
    with:
      app-name: authenticator
      runner: ubuntu-24.04
    secrets: inherit

  deploy:
    needs: [ docker-build-release ]
    uses: poznit/workflows/.github/workflows/template-deployment.yml@main
    with:
      compose_file: docker-compose.yml
      compose_override_file: docker-compose.override.yml
      compose_override_file_content: |
        services:
          app:
            image: ${{ secrets.DOCKERHUB_USER }}/authenticator:${{ github.sha }}
            build: {}
      deployment_folder: "./deploy"
