name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cargo lock check
      run: cargo check --locked

  docker-build-release:
    needs: checks
    uses: poznit/workflows/.github/workflows/template-build-release.yml@main
    with:
      app-name: authenticator
      runner: ubuntu-24.04
    secrets: inherit

  deploy:
    needs: [ docker-build-release ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare deployment
        uses: poznit/workflows/.github/actions/prepare-deploy@main
      - name: Create override file
        run: |
          cat > docker-compose.override.yml << EOL
          services:
            backend:
              image: ${{ secrets.DOCKERHUB_USER }}/authenticator:${{ github.sha }}
              build: {}
          EOL
      - name: deploy
        uses: poznit/workflows/.github/actions/deploy@main
        with:
          compose_file: docker-compose.yml
          compose_override_file: docker-compose.override.yml
          deployment_folder: "~/.deploy"
