name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cargo lock check
      run: cargo check --locked

  docker-build-release:
    needs: checks
    uses: poznit/workflows/.github/workflows/template-build-release.yml@main
    with:
      app-name: authenticator
      runner: ubuntu-24.04
    secrets: inherit

  deploy:
    needs: [ docker-build-release ]
    runs-on: ubuntu-latest
    steps:
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: ".deploy/${{ github.event.repository.name }}/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/.deploy/${{ github.event.repository.name }}
            docker compose stop
            docker compose rm -f
            docker rmi $(docker images -a -q)
            docker compose pull
            docker compose up -d
