name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 10 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cargo lock check
      run: cargo check --locked

  build-release-app:
    needs: checks
    uses: poznit/workflows/.github/workflows/template-build-release.yml@v1.0.0
    with:
      app-name: authenticator
      runner: ubuntu-24.04
    secrets: inherit

  build-release-flyway:
    needs: checks
    uses: poznit/workflows/.github/workflows/template-build-release.yml@v1.0.0
    with:
      working-directory: ./db
      app-name: authenticator-flyway
      runner: ubuntu-24.04
    secrets: inherit

  deploy:
    needs: [ build-release-app, build-release-flyway ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare deployment
        uses: poznit/workflows/.github/actions/prepare-deploy@v1.0.0
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          deployment_folder: '.~/deploy'

      - name: Create override file
        run: |
          cat > docker-compose.override.yml << EOL
          services:
            app:
              image: ${{ secrets.DOCKERHUB_USER }}/authenticator:${{ github.sha }}
            flyway:
              image: ${{ secrets.DOCKERHUB_USER }}/authenticator-flyway:${{ github.sha }}
          EOL
      - name: deploy
        uses: poznit/workflows/.github/actions/deploy@v1.0.1
        with:
          compose_file: docker-compose.yml
          compose_override_file: docker-compose.override.yml
          deployment_folder: "~/.deploy"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
